AllCops:
  NewCops: enable
 
Naming/FileName:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Security/Eval:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
