AllCops:
  NewCops: enable
 
Naming/FileName:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false